// ─────────────────────────────────────────────────────────────────────────────
// STRENGTH KNOWLEDGE LIBRARY — modular, evidence-informed coaching domains.
//
// NOT copied from any book/course/proprietary program. Summarises major coaching
// principles, physiological concepts and programming frameworks from established
// resistance-training science and publicly-available methodology.
//
// SOURCE TIERS: established | accepted | methodology | synthesis  (see running/library.mjs)
// DOMAIN SCHEMA: id, title, sourceTier, summary, coreConcepts[], adaptations[],
//   programming[], progression[], recovery[], contraindications[], relatedTo[]
// ─────────────────────────────────────────────────────────────────────────────

export const STRENGTH_DOMAINS = [
  {
    id: 'maximal_strength', title: 'Maximal Strength', sourceTier: 'established',
    summary: 'Developing peak force production via heavy loads and high movement quality.',
    coreConcepts: ['Force is built with heavy loads, low-moderate reps, full recovery.', 'Intensity (%1RM) is the primary driver; keep reps in reserve to preserve quality.'],
    adaptations: ['Neural drive, motor-unit recruitment, rate coding, tendon stiffness, myofibrillar density.'],
    programming: ['Heavy compounds 2–6 reps at 80–92% 1RM / RPE 7–9; long rests (2–5 min); each main pattern 1–3×/week.'],
    progression: ['Add load when the top set hits target reps at ≤ target RPE; intensify across a block.'],
    recovery: ['High CNS cost — full recovery between heavy sessions; avoid grinding to failure on compounds.'],
    contraindications: ['Maxing on chronic fatigue or poor technique; stacking next to hard running (interference).'],
    relatedTo: ['power_explosiveness','volume_landmarks','periodization_strength','concurrent_training'],
  },
  {
    id: 'hypertrophy', title: 'Hypertrophy', sourceTier: 'methodology',
    summary: 'Muscle growth driven by weekly hard-set volume near failure. (Schoenfeld; Israetel/RP.)',
    coreConcepts: ['Effective reps come from sets taken near failure (~0–4 RIR).', 'Think weekly sets per muscle (volume landmarks), not per session; wide rep range (~5–30) works with high effort.'],
    adaptations: ['Myofibrillar + sarcoplasmic growth, capillarisation, work capacity.'],
    programming: ['~10–20 hard sets/muscle/week (MEV→MAV); each muscle 2–3×/week; 60–80% 1RM / 0–3 RIR.'],
    progression: ['Add a set or small load weekly; back off near MRV (deload).'],
    recovery: ['Volume-driven fatigue; manage with deloads and per-muscle frequency.'],
    contraindications: ['Junk volume past MRV reduces growth and adds fatigue.'],
    relatedTo: ['volume_landmarks','autoregulation','maximal_strength'],
  },
  {
    id: 'power_explosiveness', title: 'Power & Explosiveness', sourceTier: 'established',
    summary: 'Rate of force development via explosive intent, light-moderate loads, plyometrics.',
    coreConcepts: ['Power = force × velocity; train with maximal intent and full recovery.', 'Olympic-lift variations, jumps, throws, contrast/PAP methods.'],
    adaptations: ['Rate of force development, intermuscular coordination, elastic return.'],
    programming: ['Low reps (1–5), explosive intent, 30–60% (speed) to higher (strength-speed); long rest; fresh.'],
    progression: ['Add load/complexity once technique and output are stable.'],
    recovery: ['High neural quality but low volume — never to fatigue.'],
    contraindications: ['Plyometrics on unprepared/fatigued tissue; explosive lifts when technically unsound.'],
    relatedTo: ['maximal_strength','hyrox_strength','injury_prevention_tendon'],
  },
  {
    id: 'strength_endurance', title: 'Strength Endurance', sourceTier: 'accepted',
    summary: 'Sustaining force output under fatigue — central to HYROX/DEKA and compromised running.',
    coreConcepts: ['Higher reps, shorter rest, circuit/EMOM formats build local endurance.', 'Train the specific patterns under the specific event fatigue.'],
    adaptations: ['Capillarisation, buffering, fibre endurance, work capacity.'],
    programming: ['12–25+ reps or time-based circuits at 40–70% 1RM / RPE 7–9; 1–3×/week in a conditioning phase.'],
    progression: ['Add reps/rounds or cut rest before adding load.'],
    recovery: ['Metabolically taxing; keep technique standards as fatigue rises.'],
    contraindications: ['Endless high-rep grinding that erodes movement quality.'],
    relatedTo: ['hyrox_strength','deka_strength','fitstop_method'],
  },
  {
    id: 'volume_landmarks', title: 'Volume Landmarks', sourceTier: 'methodology',
    summary: 'MEV / MAV / MRV — the recoverable volume range that drives adaptation. (Israetel/RP.)',
    coreConcepts: ['MEV (minimum effective), MAV (adaptive sweet spot), MRV (maximum recoverable).', 'Progress volume within the range; deload when approaching MRV.'],
    adaptations: ['Optimised stimulus-to-fatigue ratio across a mesocycle.'],
    programming: ['Start a block near MEV, add sets toward MAV, deload before MRV.'],
    progression: ['Weekly set additions per muscle; reset after deload at a slightly higher baseline.'],
    recovery: ['Deload is the planned drop from accumulated volume.'],
    contraindications: ['Living at MRV; adding volume without recovery to absorb it.'],
    relatedTo: ['hypertrophy','periodization_strength','recovery_fatigue'],
  },
  {
    id: 'autoregulation', title: 'Autoregulation (RIR/RPE)', sourceTier: 'methodology',
    summary: 'Adjusting load/volume to daily readiness using reps-in-reserve / RPE. (Helms; RTS.)',
    coreConcepts: ['Prescribe by RIR/RPE so effort is consistent despite day-to-day fluctuation.', 'Lets the athlete hit the intended stimulus without over/under-shooting.'],
    adaptations: ['Better stimulus consistency; reduced injury/overreach risk.'],
    programming: ['Top sets to a target RIR; back-off sets by %; auto-adjust on low-readiness days.'],
    progression: ['Lower target RIR or raise load as the block intensifies.'],
    recovery: ['Use readiness (sleep/HRV/soreness) to set the day\'s RIR.'],
    contraindications: ['Mis-rated RIR (novices) — pair with % anchors and technique standards.'],
    relatedTo: ['hypertrophy','maximal_strength','recovery_fatigue'],
  },
  {
    id: 'movement_quality', title: 'Movement Quality', sourceTier: 'accepted',
    summary: 'Sound technique and position as the foundation of force and resilience.',
    coreConcepts: ['Quality is a programmable standard, not an afterthought; earn load with positional control.', 'Regress when form degrades.'],
    adaptations: ['Motor learning, joint integrity, transferable mechanics.'],
    programming: ['Technical primers, tempo work, RIR caps that protect form; coach key positions.'],
    progression: ['Load only when quality holds at the current load.'],
    recovery: ['Fatigue degrades quality — end sets before breakdown.'],
    contraindications: ['Loading dysfunction; chasing numbers over positions.'],
    relatedTo: ['exercise_selection','injury_prevention_tendon','maximal_strength'],
  },
  {
    id: 'structural_balance', title: 'Structural Balance', sourceTier: 'accepted',
    summary: 'Balanced development across patterns to avoid asymmetry and injury.',
    coreConcepts: ['Cover squat, hinge, push, pull, carry, lunge, brace.', 'Balance push/pull and knee/hip dominance; address weak links.'],
    adaptations: ['Joint health, posture, transfer, injury resistance.'],
    programming: ['Pair pressing with pulling; include unilateral + posterior-chain work; carries for trunk.'],
    progression: ['Bias volume to lagging patterns until balanced.'],
    recovery: ['Balanced loading distributes joint stress.'],
    contraindications: ['Push-dominant or quad-dominant programs neglecting posterior chain.'],
    relatedTo: ['exercise_selection','movement_quality','injury_prevention_tendon'],
  },
  {
    id: 'exercise_selection', title: 'Exercise Selection', sourceTier: 'accepted',
    summary: 'Choosing movements by pattern, stimulus, equipment and fatigue cost.',
    coreConcepts: ['Anchor sessions with high-stimulus compounds; fill volume with lower-fatigue accessories.', 'Swap within a pattern for equipment/injury/fatigue.'],
    adaptations: ['Targeted stimulus with managed systemic fatigue.'],
    programming: ['1–2 main compounds + 2–4 accessories per session; substitute within pattern as needed.'],
    progression: ['Rotate variations across blocks to manage staleness and weak points.'],
    recovery: ['Mix high- and low-fatigue movements to control session cost.'],
    contraindications: ['All high-fatigue compounds in one session; substituting across patterns (changes the effect).'],
    relatedTo: ['structural_balance','movement_quality','hypertrophy'],
  },
  {
    id: 'periodization_strength', title: 'Strength Periodization', sourceTier: 'methodology',
    summary: 'Sequencing blocks: hypertrophy → strength → power/peak. (Bompa; block periodisation.)',
    coreConcepts: ['Accumulation (volume) → intensification (load) → realisation (peak/taper).', 'Each block potentiates the next; carry maintenance doses forward.'],
    adaptations: ['Phase-appropriate qualities expressed at the right time.'],
    programming: ['3–6 week mesocycles with a deload; intensify load while volume trends down toward a peak.'],
    progression: ['Move from general → specific; peak the target quality near the goal date.'],
    recovery: ['Deload each mesocycle; taper before a strength test/competition.'],
    contraindications: ['Peaking too early; skipping the volume base.'],
    relatedTo: ['volume_landmarks','maximal_strength','fitstop_method'],
  },
  {
    id: 'concurrent_training', title: 'Concurrent Training', sourceTier: 'established',
    summary: 'Managing endurance↔strength interference when training both. (Hickson; Coffey & Hawley.)',
    coreConcepts: ['Endurance can blunt strength/power gains (AMPK vs mTOR + residual fatigue); mostly fatigue-mediated.', 'Lower-body endurance interferes most with leg strength.'],
    adaptations: ['Both can develop when sequenced well; bias to the phase priority.'],
    programming: ['Separate hard runs from heavy lower-body lifts ≥6–24 h; prioritise the goal session first if same day.'],
    progression: ['Shift strength:endurance balance by phase rather than maxing both at once.'],
    recovery: ['Add recovery when stacking modalities; watch lower-body load.'],
    contraindications: ['VO₂max work adjacent to a heavy squat day.'],
    relatedTo: ['recovery_fatigue','maximal_strength','fitstop_method'],
  },
  {
    id: 'recovery_fatigue', title: 'Recovery & Fatigue Management', sourceTier: 'established',
    summary: 'Sleep, fuel, deloads and autoregulation that let strength adapt.',
    coreConcepts: ['Adaptation happens in recovery; manage weekly + block-level fatigue, not just per-session.', 'Deloads are part of the stimulus.'],
    adaptations: ['Realised strength/size gains; reduced overreach/injury.'],
    programming: ['Hard/easy sequencing; deload every 3–5 weeks; protein ~1.6–2.2 g/kg/day.'],
    progression: ['Let readiness gate progression; resume after deload at a higher baseline.'],
    recovery: ['Sleep is primary; post-session protein supports MPS.'],
    contraindications: ['Heavy/high-volume work on chronic fatigue or under-fuelling.'],
    relatedTo: ['volume_landmarks','autoregulation','concurrent_training'],
  },
  {
    id: 'injury_prevention_tendon', title: 'Injury Prevention & Tendon Health', sourceTier: 'established',
    summary: 'Tissue capacity and load progression to train pain-free.',
    coreConcepts: ['Tendon/bone adapt slower than muscle/strength — the usual injury gap.', 'Tendons respond to slow, heavy and high-load isometrics.'],
    adaptations: ['Tendon stiffness, bone density, connective-tissue tolerance.'],
    programming: ['Ramp load conservatively; include tendon-specific loading; full ROM with control.'],
    progression: ['Build tissue tolerance before chasing load, especially returning from layoff.'],
    recovery: ['Heed niggles; deload connective tissue periodically.'],
    contraindications: ['Load spikes; ballistic work on unprepared tendons.'],
    relatedTo: ['movement_quality','recovery_fatigue','power_explosiveness'],
  },
  {
    id: 'fitstop_method', title: 'Fitstop (as strength methodology)', sourceTier: 'methodology',
    summary: 'Fitstop\'s block as a complete strength programming system. (User-provided: BLOCK C 2026.)',
    coreConcepts: ['12-week block as 4×3-week phases: BASE → BUILD → PERFORMANCE → PEAK.', 'Fixed weekly split: Mon PERFORM, Tue LIFT, Wed CONDITION, Thu PERFORM, Fri LIFT, Sat SWEAT, Sun rest.', 'Main lifts (Back Squat, Deadlift, Bench, Chin-Up) intensify: BASE variations(RIR 1–3) → BUILD 5RM → PERFORMANCE 3RM → PEAK 1RM.'],
    adaptations: ['Concurrent strength + conditioning; main-lift maximal strength by PEAK; work capacity via PERFORM/CONDITION/SWEAT.'],
    programming: ['Use the real BLOCK C sessions (LIFT = main lift + 3–4 round A/B/C accessory supersets). When Fitstop is the strength program, its LIFT days ARE the strength stimulus — do not add a separate generic strength block.'],
    progression: ['Follow the block\'s phase RM progression; skills (KB, T2B, Cleans) and fitness intervals progress to PEAK time trials.'],
    recovery: ['6 training days/week — high combined load; manage carefully when adding endurance (concurrent interference).'],
    contraindications: ['Layering an additional heavy strength block on top of Fitstop; stacking hard runs next to LIFT days.'],
    relatedTo: ['maximal_strength','strength_endurance','concurrent_training','periodization_strength'],
  },
  {
    id: 'hyrox_strength', title: 'HYROX Strength', sourceTier: 'methodology',
    summary: 'Strength qualities for HYROX stations (sled, wall balls, lunges, carries).',
    coreConcepts: ['Stations demand sustained submaximal output — strength-endurance, not 1RM.', 'Adequate maximal strength makes station loads feel submaximal; grip + posterior chain are common limiters.'],
    adaptations: ['Strength-endurance, grip, sled/lunge capacity, work tolerance under fatigue.'],
    programming: ['Submaximal high-volume station-specific work; some max strength to raise the ceiling; 1–2×/week specific.'],
    progression: ['Add reps/rounds or reduce rest before load; build toward race simulation.'],
    recovery: ['Combine with running carefully (concurrent load is high).'],
    contraindications: ['Only training heavy strength while neglecting station endurance/grip.'],
    relatedTo: ['strength_endurance','concurrent_training','deka_strength'],
  },
  {
    id: 'deka_strength', title: 'DEKA Strength', sourceTier: 'methodology',
    summary: 'Strength/power-endurance across DEKA zones (functional movements under fatigue).',
    coreConcepts: ['Mixed-modal zones rotate movement patterns under fatigue; transitions matter.', 'Shore up the weakest zone rather than rehearsing strengths.'],
    adaptations: ['Power-endurance, work capacity, movement efficiency across zones.'],
    programming: ['Circuit/round-based functional work in the zone movements; submaximal sustainable output.'],
    progression: ['Add rounds/zones or reduce transition rest; rehearse the format.'],
    recovery: ['Treat full simulations like hard races; manage total load.'],
    contraindications: ['Going out too hot in early zones; neglecting the weakest movement.'],
    relatedTo: ['strength_endurance','hyrox_strength','concurrent_training'],
  },
];

export const STRENGTH_COACH_EV = {
  id: 'coach_ev_strength', title: 'Coach EV — Strength Philosophy', sourceTier: 'synthesis',
  principles: [
    'Anchor every session with a compound; earn load with positional quality.',
    'Program weekly volume within the recoverable range; deload before you have to.',
    'Autoregulate to readiness; intensity preserves strength when volume must drop.',
    'When running concurrently, protect the priority quality and separate competing stimuli.',
  ],
};

export const STRENGTH_KB_VERSION = 1;
