// Knowledge domain: CORE — cross-cutting coaching principles that govern every
// specialist module. Established training science. No proprietary methodology.

export const core = [
  {
    id: 'core.progressive_overload',
    domain: 'core', version: 1,
    title: 'Progressive Overload',
    summary: 'Adaptation requires a training stimulus that gradually exceeds what the body is currently accustomed to.',
    principles: [
      'Increase one variable at a time: volume, intensity, density, or complexity.',
      'Smallest effective progression beats largest tolerable progression.',
      'Progression must be earned by recovery, not imposed on a calendar.',
    ],
    prescription: { intensity: 'Raise load/pace only when current load is consolidated.', frequency: 'Re-evaluate weekly.', progression: 'Add ~5–10% volume/week; hold or deload every 3–5 weeks.' },
    cautions: ['Progressing multiple variables at once obscures cause and inflates injury risk.'],
    appliesTo: ['running','strength','hybrid','hyrox','fitstop'],
    tags: ['overload','progression','foundation'],
    sources: ['Established science: general adaptation syndrome (Selye); ACSM progression guidance.'],
  },
  {
    id: 'core.specificity',
    domain: 'core', version: 1,
    title: 'Specificity (SAID)',
    summary: 'Adaptations are specific to the demands imposed — training must resemble the goal as the goal nears.',
    principles: [
      'General work builds capacity early; specific work sharpens it late.',
      'Transfer falls as the training drifts from the event demands.',
      'Define the event demands first, then reverse-engineer the work.',
    ],
    prescription: { progression: 'Move from general → specific across the macrocycle; peak specificity in the final block.' },
    cautions: ['Too much specificity too early plateaus and bores; too little late under-prepares.'],
    appliesTo: ['running','strength','hybrid','hyrox','deka','fitstop'],
    tags: ['specificity','transfer','said'],
    sources: ['Established science: SAID principle; specificity literature.'],
  },
  {
    id: 'core.individualisation',
    domain: 'core', version: 1,
    title: 'Individualisation',
    summary: 'The same program produces different results in different athletes; training must fit history, recovery, constraints and response.',
    principles: [
      'Start from the athlete model (history, baselines, availability, injuries), not a template.',
      'Adjust to demonstrated response, not assumed response.',
      'Constraints (time, equipment, life) are inputs, not excuses.',
    ],
    prescription: { frequency: 'Re-personalise as new training data and outcomes arrive.' },
    cautions: ['Copy-paste programming ignores recoverability and injury history.'],
    appliesTo: ['running','strength','hybrid','hyrox','deka','fitstop'],
    tags: ['individualisation','personalisation'],
    sources: ['Established science: inter-individual variability in training response (e.g. HERITAGE study).'],
  },
  {
    id: 'core.recoverability',
    domain: 'core', version: 1,
    title: 'Fatigue, Recovery & the Fitness–Fatigue Model',
    summary: 'Performance is fitness minus fatigue; adaptation happens during recovery, so load must be balanced against the ability to absorb it.',
    principles: [
      'Hard days hard, easy days easy — avoid the chronic moderate grind.',
      'Manage weekly and block-level fatigue, not just per-session.',
      'Deloads are part of the stimulus, not a break from it.',
    ],
    prescription: { frequency: 'Sequence hard/easy; insert deload every 3–5 weeks.', progression: 'Let recovery markers (HRV, sleep, RPE drift) gate progression.' },
    cautions: ['Accumulating fatigue masks fitness and precedes injury/illness.'],
    appliesTo: ['running','strength','hybrid','hyrox','deka','fitstop'],
    tags: ['fatigue','recovery','fitness-fatigue'],
    sources: ['Established science: Banister fitness-fatigue model; Bannister/Calvert impulse-response.'],
  },
  {
    id: 'core.adaptation_timelines',
    domain: 'core', version: 1,
    title: 'Adaptation Timelines',
    summary: 'Different systems adapt on different clocks — programming must respect what can change in the time available.',
    principles: [
      'Neural/strength gains: days–weeks. Aerobic/mitochondrial: weeks–months. Connective tissue/tendon: months. Hypertrophy: weeks–months.',
      'Set goals and phase lengths against realistic adaptation rates.',
    ],
    prescription: { progression: 'Match block length to the slowest target adaptation in the phase.' },
    cautions: ['Tendons/bone adapt slower than muscle/fitness — the usual injury gap when volume jumps.'],
    appliesTo: ['running','strength','hybrid','hyrox','deka'],
    tags: ['timelines','adaptation','planning'],
    sources: ['Established science: tissue adaptation timelines; tendon mechanobiology literature.'],
  },
];
