// Knowledge domain: HYROX — race demands, stations, compromised running, pacing,
// race simulation, progression. Event format is PUBLIC fact; coaching method is
// established endurance/strength-endurance science. No proprietary methodology.

export const hyrox = [
  {
    id: 'hyrox.event_demands',
    domain: 'hyrox', version: 1,
    title: 'HYROX Event Demands (Format)',
    summary: 'HYROX = 8 × 1 km runs, each followed by one functional station, in a fixed order — a ~60–90 min hybrid endurance + strength-endurance race.',
    principles: [
      'Fixed station order: SkiErg → Sled Push → Sled Pull → Burpee Broad Jumps → Row → Farmers Carry → Sandbag Lunges → Wall Balls.',
      'It is fundamentally a running race interrupted by strength-endurance stations.',
      'Pro division uses heavier loads than Open; demands scale accordingly.',
    ],
    prescription: { progression: 'Train all three: running under fatigue, station capacity, and transitions.' },
    cautions: ['Treating it as pure strength or pure running both fail — it is the blend.'],
    appliesTo: ['hyrox','hybrid'],
    tags: ['event','format','stations','demands'],
    sources: ['Public event format: official HYROX race structure (8×1km + 8 stations).'],
  },
  {
    id: 'hyrox.compromised_running',
    domain: 'hyrox', version: 1,
    title: 'Compromised Running',
    summary: 'The decisive HYROX skill is running well with pre-fatigued legs and elevated heart rate straight off a station.',
    principles: [
      'Most time is in the runs; running ability under fatigue separates finishers.',
      'Train running immediately after strength/station work (brick sessions).',
      'Pacing the first runs conservatively protects the back-half runs.',
    ],
    prescription: { intensity: 'Goal race pace under fatigue; Z3–4 on runs.', duration: 'Brick intervals: station block → 400–1000 m run, repeated.', frequency: '1–2 compromised-running sessions/week in the specific block.', progression: 'Increase run quality off stations week to week.' },
    cautions: ['Practising fresh running only leaves athletes unprepared for the real demand.'],
    appliesTo: ['hyrox','hybrid'],
    tags: ['compromised-running','brick','pacing','specificity'],
    sources: ['Established science: brick/transition training; specificity applied to HYROX format.'],
  },
  {
    id: 'hyrox.station_capacity',
    domain: 'hyrox', version: 1,
    title: 'Station Strength-Endurance',
    summary: 'Each station demands sustained submaximal output (sled push/pull, wall balls, lunges, carries) — strength-endurance, not 1RM strength.',
    principles: [
      'Build capacity in the exact movements (sled, wall ball, lunge, carry, SkiErg/row).',
      'Grip and posterior-chain endurance are common limiters.',
      'Adequate maximal strength makes station loads feel submaximal — but capacity is king.',
    ],
    prescription: { intensity: 'Submaximal, high-volume, short-rest in station patterns.', duration: 'Time/round-based circuits in race movements.', frequency: '1–2×/week.', progression: 'Add reps/rounds or reduce rest before adding load.' },
    cautions: ['Only training heavy strength leaves station endurance and grip underprepared.'],
    appliesTo: ['hyrox','hybrid','deka'],
    tags: ['stations','strength-endurance','grip','capacity'],
    sources: ['Established science: strength-endurance + specificity applied to public station list.'],
  },
  {
    id: 'hyrox.pacing_strategy',
    domain: 'hyrox', version: 1,
    title: 'Race Pacing & Strategy',
    summary: 'Even, controlled effort with deliberately conservative early stations/runs beats a fast start that blows up the back half.',
    principles: [
      'Negative or even effort split; bank nothing early.',
      'Sleds and wall balls are common blow-up points — pace them.',
      'Plan transitions and station break-up (e.g. wall-ball sets) in advance.',
    ],
    prescription: { intensity: 'Hold sustainable effort; avoid red-lining early stations.', progression: 'Rehearse the plan in race simulations.' },
    cautions: ['Going out hard on the SkiErg/first runs is the classic positive-split error.'],
    appliesTo: ['hyrox'],
    tags: ['pacing','strategy','race-execution'],
    sources: ['Established science: even/negative-split pacing applied to the HYROX format.'],
  },
  {
    id: 'hyrox.race_simulation',
    domain: 'hyrox', version: 1,
    title: 'Race Simulation & Progression',
    summary: 'Periodic partial or full simulations build specific fitness, pacing skill and mental rehearsal — sparingly, given their cost.',
    principles: [
      'Use partial simulations (e.g. 4-station halves) more often than full ones.',
      'Full simulations are high-fatigue — schedule like a hard race, then recover.',
      'Progress from segments → halves → full as the event nears.',
    ],
    prescription: { frequency: 'Partial sims periodically; 1–2 full sims in the final block.', progression: 'Build simulation completeness toward race day; taper after.' },
    cautions: ['Frequent full simulations accumulate excessive fatigue.'],
    appliesTo: ['hyrox'],
    tags: ['simulation','specificity','peaking'],
    sources: ['Established science: specificity + fatigue management applied to race rehearsal.'],
  },

  {
    id: 'hyrox.periodisation',
    domain: 'hyrox', version: 2,
    title: 'HYROX Periodisation',
    summary: 'A race-prep cycle runs 8–12 weeks across four phases: Base → Build → Specific → Taper.',
    principles: [
      'Base (4–6 wks): aerobic capacity and station technique with perfect form; easy running volume, movement competency.',
      'Build: raise volume and introduce race-pace transitions.',
      'Specific: approximate race conditions with full or half simulations, race-pace running, exact station standards.',
      'Taper: drop volume sharply in the final 7–10 days; keep short sharp efforts so sharpness is retained.',
      'Deload every few weeks — cut volume roughly 40–50%.',
      'Integrated periodisation develops running and strength simultaneously while managing fatigue; it is not running workouts and lifting sessions placed side by side.',
    ],
    prescription: {
      weeklySessions: '4–6 for committed athletes (2–3 strength, 2–3 cardio, 1 race simulation); beginners 3–4, scaling after week 4.',
      timeSplit: 'Approximately 60% of weekly training time on running, 40% on stations — mirroring race composition.',
      simulations: 'At least two per cycle — a full simulation around week 9 and a half around week 11 of a 12-week block.',
      progression: 'Final 3–4 weeks tilt toward specificity.',
    },
    cautions: [
      'Long-term project: consistency beats short bursts.',
      'Concurrent load is high — deloads are part of the prescription, not optional.',
    ],
    appliesTo: ['hyrox','hybrid'],
    tags: ['periodisation','phases','taper','deload','simulation'],
    sources: [
      'Vibefam — "How to build a HYROX race-prep program" (2026): 8–12 wk cycle, 4 phases, 4–6 sessions/wk, 60/40 split, simulations at wk 9 and 11.',
      'rb100.fitness — "Periodisation for HYROX: Structuring Your Training Year".',
      'RoxZone Training — HYROX training methodology; base 4–6 wks, deload 40–50% volume cut.',
      'coachway.io — "How to Coach HYROX Athletes" (2026).',
    ],
  },
  {
    id: 'hyrox.pacing',
    domain: 'hyrox', version: 2,
    title: 'HYROX Pacing and the Roxzone',
    summary: 'The race is won by even or slightly negative splits; the commonest failure is running run 1 far too fast.',
    principles: [
      'Run the first kilometre 10–15 s slower than goal pace.',
      'Athletes whose first 1 km is >10 s/km faster than their average slow by 18–22% by run 8.',
      'Even pacing (within 10% variance across runs) finishes 5–10% faster than sprint-early-fade-late at the same average output.',
      'The best races are negative split: the second 4 km + 4 stations match or beat the first.',
      'The roxzone is timed. Most athletes lose 30–90 s per race by walking it or treating it as rest.',
      'Do not sprint out of a station only to crash 200 m later — smart pacing is trainable in brick sessions.',
    ],
    prescription: {
      progression: 'Rehearse goal race pace in brick sessions and simulations; practise transitions deliberately rather than resting in them.',
    },
    cautions: ['"Fly and die" is the single most common race-day error.'],
    appliesTo: ['hyrox'],
    tags: ['pacing','roxzone','transitions','strategy','race-day'],
    sources: [
      'HyroxDataLab — pacing analysis: >10 s/km fast first km → 18–22% slowdown by run 8; even pacing 5–10% faster.',
      'RoxZone Training — race-day strategy: roxzone losses 30–90 s.',
      'Hyrox Vault — pacing strategy; negative-split guidance.',
      'HybridProCoach — common beginner mistakes.',
    ],
  },
  {
    id: 'hyrox.compromised_running_dose',
    domain: 'hyrox', version: 2,
    title: 'Compromised Running — Dose',
    summary: 'The highest-leverage HYROX-specific session, trained 1–2× per week from at least 8 weeks out.',
    principles: [
      'Compromised running is a different neuromuscular experience from fresh running and must be trained specifically.',
      'Leg-heavy stations (sled push, sandbag lunges, wall balls, burpee broad jumps) most degrade the following run.',
    ],
    prescription: {
      session: '4–6 rounds of 800 m–1 km at goal race pace paired with a leg-heavy station; 1–2 min between rounds to mimic transitions.',
      alternatives: 'Simpler formats work: finish a gym circuit with a 400 m treadmill run; 50 burpee broad jumps → 1 km run × 3.',
      stationIntervals: 'Wall balls 5×20 @ 60 s; SkiErg 5×200 m @ 90 s; sled push 6×25 m @ 90 s.',
      frequency: '1–2× per week, starting at least 8 weeks out.',
    },
    cautions: ['Only practising fresh running leaves the decisive quality untrained.'],
    appliesTo: ['hyrox','hybrid'],
    tags: ['compromised-running','brick','dose','stations'],
    sources: [
      'compromisedrunning.com — "How to Structure your Hyrox Training" and "What is Compromised Running?".',
      'coachway.io — "How to Coach HYROX Athletes" (2026): 4–6 rounds, 800 m–1 km, 1–2 min transitions.',
      'Xendurance — "Compromised Running: Hyrox\'s Biggest Game-Changer".',
      'hyroxfitness.com — station interval formats.',
    ],
  },
];
