// Knowledge domain: HYROX — race demands, stations, compromised running, pacing,
// race simulation, progression. Event format is PUBLIC fact; coaching method is
// established endurance/strength-endurance science. No proprietary methodology.

export const hyrox = [
  {
    id: 'hyrox.event_demands',
    domain: 'hyrox', version: 1,
    title: 'HYROX Event Demands (Format)',
    summary: 'HYROX = 8 × 1 km runs, each followed by one functional station, in a fixed order — a ~60–90 min hybrid endurance + strength-endurance race.',
    principles: [
      'Fixed station order: SkiErg → Sled Push → Sled Pull → Burpee Broad Jumps → Row → Farmers Carry → Sandbag Lunges → Wall Balls.',
      'It is fundamentally a running race interrupted by strength-endurance stations.',
      'Pro division uses heavier loads than Open; demands scale accordingly.',
    ],
    prescription: { progression: 'Train all three: running under fatigue, station capacity, and transitions.' },
    cautions: ['Treating it as pure strength or pure running both fail — it is the blend.'],
    appliesTo: ['hyrox','hybrid'],
    tags: ['event','format','stations','demands'],
    sources: ['Public event format: official HYROX race structure (8×1km + 8 stations).'],
  },
  {
    id: 'hyrox.compromised_running',
    domain: 'hyrox', version: 1,
    title: 'Compromised Running',
    summary: 'The decisive HYROX skill is running well with pre-fatigued legs and elevated heart rate straight off a station.',
    principles: [
      'Most time is in the runs; running ability under fatigue separates finishers.',
      'Train running immediately after strength/station work (brick sessions).',
      'Pacing the first runs conservatively protects the back-half runs.',
    ],
    prescription: { intensity: 'Goal race pace under fatigue; Z3–4 on runs.', duration: 'Brick intervals: station block → 400–1000 m run, repeated.', frequency: '1–2 compromised-running sessions/week in the specific block.', progression: 'Increase run quality off stations week to week.' },
    cautions: ['Practising fresh running only leaves athletes unprepared for the real demand.'],
    appliesTo: ['hyrox','hybrid'],
    tags: ['compromised-running','brick','pacing','specificity'],
    sources: ['Established science: brick/transition training; specificity applied to HYROX format.'],
  },
  {
    id: 'hyrox.station_capacity',
    domain: 'hyrox', version: 1,
    title: 'Station Strength-Endurance',
    summary: 'Each station demands sustained submaximal output (sled push/pull, wall balls, lunges, carries) — strength-endurance, not 1RM strength.',
    principles: [
      'Build capacity in the exact movements (sled, wall ball, lunge, carry, SkiErg/row).',
      'Grip and posterior-chain endurance are common limiters.',
      'Adequate maximal strength makes station loads feel submaximal — but capacity is king.',
    ],
    prescription: { intensity: 'Submaximal, high-volume, short-rest in station patterns.', duration: 'Time/round-based circuits in race movements.', frequency: '1–2×/week.', progression: 'Add reps/rounds or reduce rest before adding load.' },
    cautions: ['Only training heavy strength leaves station endurance and grip underprepared.'],
    appliesTo: ['hyrox','hybrid','deka'],
    tags: ['stations','strength-endurance','grip','capacity'],
    sources: ['Established science: strength-endurance + specificity applied to public station list.'],
  },
  {
    id: 'hyrox.pacing_strategy',
    domain: 'hyrox', version: 1,
    title: 'Race Pacing & Strategy',
    summary: 'Even, controlled effort with deliberately conservative early stations/runs beats a fast start that blows up the back half.',
    principles: [
      'Negative or even effort split; bank nothing early.',
      'Sleds and wall balls are common blow-up points — pace them.',
      'Plan transitions and station break-up (e.g. wall-ball sets) in advance.',
    ],
    prescription: { intensity: 'Hold sustainable effort; avoid red-lining early stations.', progression: 'Rehearse the plan in race simulations.' },
    cautions: ['Going out hard on the SkiErg/first runs is the classic positive-split error.'],
    appliesTo: ['hyrox'],
    tags: ['pacing','strategy','race-execution'],
    sources: ['Established science: even/negative-split pacing applied to the HYROX format.'],
  },
  {
    id: 'hyrox.race_simulation',
    domain: 'hyrox', version: 1,
    title: 'Race Simulation & Progression',
    summary: 'Periodic partial or full simulations build specific fitness, pacing skill and mental rehearsal — sparingly, given their cost.',
    principles: [
      'Use partial simulations (e.g. 4-station halves) more often than full ones.',
      'Full simulations are high-fatigue — schedule like a hard race, then recover.',
      'Progress from segments → halves → full as the event nears.',
    ],
    prescription: { frequency: 'Partial sims periodically; 1–2 full sims in the final block.', progression: 'Build simulation completeness toward race day; taper after.' },
    cautions: ['Frequent full simulations accumulate excessive fatigue.'],
    appliesTo: ['hyrox'],
    tags: ['simulation','specificity','peaking'],
    sources: ['Established science: specificity + fatigue management applied to race rehearsal.'],
  },
];
