// Knowledge domain: RECOVERY — HRV, sleep, fatigue trends, taper readiness,
// connective-tissue adaptation, recovery recommendations. Established science.

export const recovery = [
  {
    id: 'recovery.sleep',
    domain: 'recovery', version: 1,
    title: 'Sleep as the Primary Recovery Driver',
    summary: 'Sleep is the highest-leverage recovery input; chronic shortfall degrades adaptation, performance and injury resistance.',
    principles: [
      'Target ~7–9 h; consistency of timing matters as much as duration.',
      'Acute deprivation impairs power, endurance and decision-making; chronic shortfall blunts adaptation.',
      'Protect sleep before adding training load.',
    ],
    prescription: { progression: 'Treat poor sleep as a reason to reduce planned intensity, not push through.' },
    cautions: ['Hard sessions on chronic sleep debt raise injury/illness risk.'],
    appliesTo: ['running','strength','hybrid','hyrox','deka','fitstop'],
    tags: ['sleep','recovery','readiness'],
    sources: ['Established science: sleep-and-performance literature (Walker; sport sleep reviews).'],
  },
  {
    id: 'recovery.hrv',
    domain: 'recovery', version: 1,
    title: 'HRV-Guided Readiness',
    summary: 'Heart-rate variability trends reflect autonomic recovery; falling HRV with rising RHR signals accumulating fatigue.',
    principles: [
      'Use trends and baselines, not single-day values.',
      'Suppressed HRV + elevated resting HR ⇒ ease intensity; healthy trend ⇒ green light.',
      'Context HRV with sleep, soreness and life stress.',
    ],
    prescription: { frequency: 'Daily AM reading; act on multi-day trends.', progression: 'Gate hard sessions on readiness; auto-regulate volume.' },
    cautions: ['Reacting to noise (single readings) creates erratic programming.'],
    appliesTo: ['running','strength','hybrid','hyrox','deka'],
    tags: ['hrv','readiness','autoregulation','rhr'],
    sources: ['Established science: HRV-guided training (Plews/Buchheit; Kiviniemi).'],
  },
  {
    id: 'recovery.fatigue_monitoring',
    domain: 'recovery', version: 1,
    title: 'Fatigue Monitoring & Autoregulation',
    summary: 'Simple subjective + objective markers catch overreaching early so load can be adjusted before it becomes injury or burnout.',
    principles: [
      'Watch session-RPE drift, mood, soreness, RHR, motivation, performance decrements.',
      'Functional overreaching (planned, brief) is useful; non-functional overreaching is not.',
      'Autoregulate: adjust today\'s session to today\'s state.',
    ],
    prescription: { frequency: 'Log feel + load each session; review weekly.', progression: 'Reduce/insert recovery when multiple markers trend negative.' },
    cautions: ['Ignoring early warning signs is how athletes reach overtraining syndrome.'],
    appliesTo: ['running','strength','hybrid','hyrox','deka','fitstop'],
    tags: ['fatigue','autoregulation','monitoring','rpe'],
    sources: ['Established science: overreaching/overtraining continuum; session-RPE monitoring (Foster).'],
  },
  {
    id: 'recovery.connective_tissue',
    domain: 'recovery', version: 1,
    title: 'Connective-Tissue & Bone Adaptation',
    summary: 'Tendon, ligament and bone adapt slower than muscle and aerobic fitness — the lag that drives most overuse injuries.',
    principles: [
      'Cap rate of load increase (e.g. running volume ~≤10%/week) to let tissue catch up.',
      'Tendons respond to slow, heavy and high-load isometric work.',
      'Returning from layoff: rebuild tissue tolerance before chasing fitness.',
    ],
    prescription: { progression: 'Ramp impact volume conservatively; include tendon-specific loading.' },
    cautions: ['Fitness outpacing tissue tolerance = the classic stress-injury setup.'],
    appliesTo: ['running','hybrid','hyrox','deka'],
    tags: ['tendon','bone','injury-prevention','loading'],
    sources: ['Established science: tendon mechanobiology; bone-loading / stress-injury literature.'],
  },
  {
    id: 'recovery.recommendations',
    domain: 'recovery', version: 1,
    title: 'Active Recovery & Between-Session Recovery',
    summary: 'Light movement, nutrition timing, hydration and downtime accelerate readiness between hard efforts.',
    principles: [
      'Easy aerobic/mobility work can aid recovery without adding fatigue.',
      'Post-session protein + carbohydrate supports repair and refuelling.',
      'Most recovery is sleep, food and time — gadgets are marginal.',
    ],
    prescription: { frequency: 'Active recovery as needed around hard days.', progression: 'Use recovery modalities to enable the next quality session, not to add volume.' },
    cautions: ['"Recovery sessions" that turn moderate defeat the purpose.'],
    appliesTo: ['running','strength','hybrid','hyrox','deka','fitstop'],
    tags: ['active-recovery','nutrition-timing','hydration'],
    sources: ['Established science: recovery-modality reviews; post-exercise nutrition (ISSN).'],
  },
];
