// Knowledge domain: RUNNING
// Established endurance science. Every entry cites the public framework it derives from.
// No proprietary methodology. Authored to be programmable (see `prescription`).

export const running = [
  {
    id: 'running.intensity_distribution',
    domain: 'running', version: 1,
    title: 'Intensity Distribution (Polarised / 80-20)',
    summary: 'Most endurance volume should be genuinely easy; a small, protected slice is hard. Avoid the grey "moderate" zone.',
    principles: [
      'Roughly 80% of sessions/time at low intensity (Zone 1–2), ~20% at high intensity (Zone 4–5).',
      'Easy must be easy — controlled by HR/pace/talk-test, not ego.',
      'The "moderate" middle (threshold-ish but not threshold) accumulates fatigue without proportional adaptation; spend it deliberately, not by accident.',
    ],
    prescription: {
      intensity: 'Easy: Zone 1–2 (<~75% HRmax). Hard: Zone 4–5 (threshold→VO2).',
      duration: 'Easy sessions form the bulk of weekly minutes.',
      frequency: 'Per week: ≥1 but usually ≤2–3 quality sessions; the rest easy.',
      progression: 'Add easy volume first; add quality density only once easy volume is consistent.',
    },
    cautions: ['Two hard days back-to-back blunts adaptation and raises injury risk.', 'Drifting easy runs into moderate is the most common error.'],
    appliesTo: ['running','hybrid','hyrox'],
    tags: ['intensity','polarised','aerobic','distribution'],
    sources: ['Established science: Seiler — polarised training; Stephen Seiler intensity-distribution research.'],
  },
  {
    id: 'running.aerobic_base',
    domain: 'running', version: 1,
    title: 'Aerobic Base / Zone 2 Development',
    summary: 'Low-intensity volume builds mitochondrial density, capillarisation, fat oxidation and durability — the foundation everything else sits on.',
    principles: [
      'Zone 2 = conversational, nasal-breathing-capable, sustainable for hours.',
      'Base is built by frequency and total time at easy intensity, not by occasional long efforts.',
      'Durability (late-race economy) comes from accumulated easy volume.',
    ],
    prescription: {
      intensity: 'Zone 2 (~65–75% HRmax; ~2 mmol/L lactate).',
      duration: '30–90 min depending on athlete and phase.',
      frequency: '2–5×/week as the volume backbone.',
      progression: 'Increase weekly easy volume ~5–10%/week; hold every 3–4 weeks.',
    },
    cautions: ['Running base too fast is the defining mistake of intermediate runners.'],
    appliesTo: ['running','hybrid','hyrox'],
    tags: ['aerobic','zone2','base','volume'],
    sources: ['Established science: aerobic base / MAF principles; ACSM endurance guidance.'],
  },
  {
    id: 'running.threshold',
    domain: 'running', version: 1,
    title: 'Threshold / Lactate-Threshold Development',
    summary: 'Training at/near lactate threshold raises the pace an athlete can hold before fatigue accelerates — the single biggest lever for most race distances 10K→marathon.',
    principles: [
      'Threshold = "comfortably hard", ~the fastest pace sustainable ~60 min.',
      'Best developed via tempo runs and cruise intervals, not all-out efforts.',
      'Improves the fraction of VO2max sustainable over race duration.',
    ],
    prescription: {
      intensity: 'Threshold pace / Zone 3–4 / ~RPE 7–8 / ~85–90% HRmax.',
      duration: 'Continuous 20–40 min, or cruise intervals (e.g. 3–5×8–10 min, short jog).',
      frequency: '1×/week typically; up to 2 in a threshold-focused block.',
      progression: 'Extend time-at-threshold week to week before increasing pace.',
    },
    cautions: ['Overusing threshold turns a program into chronic "grey zone" grind.'],
    appliesTo: ['running','hybrid','hyrox'],
    tags: ['threshold','tempo','lactate'],
    sources: ["Established science: Daniels' Running Formula (threshold/T-pace); cruise-interval methodology."],
  },
  {
    id: 'running.vo2max',
    domain: 'running', version: 1,
    title: 'VO2max Intervals',
    summary: 'Short, hard intervals near maximal aerobic power raise the ceiling (VO2max) and running economy at speed.',
    principles: [
      'Work near vVO2max in repeats that accumulate time at high %VO2max.',
      'Recoveries long enough to keep quality, short enough to keep aerobic stimulus.',
      'High stimulus → use sparingly and in dedicated phases.',
    ],
    prescription: {
      intensity: 'VO2max pace / Zone 5 / ~RPE 9 / ~95–100% HRmax.',
      duration: 'Reps 3–5 min (e.g. 5×3 min) or shorter (e.g. 8–12×400–800m).',
      frequency: '1×/week in a VO2-focused block; rarely 2.',
      progression: 'Add reps/total work before adding speed; cap the block at ~3–6 weeks.',
    },
    cautions: ['Most injury-prone session type — requires an aerobic base first.', 'Never stack on a heavy-lift day for hybrid athletes.'],
    appliesTo: ['running','hybrid','hyrox'],
    tags: ['vo2max','intervals','speed'],
    sources: ['Established science: Billat (vVO2max); classic interval physiology.'],
  },
  {
    id: 'running.long_run',
    domain: 'running', version: 1,
    title: 'Long Run',
    summary: 'The weekly long run builds endurance, fat oxidation, mental durability and (for marathon) glycogen/fueling adaptation.',
    principles: [
      'Mostly easy; long-run duration matters more than pace for base.',
      'Distance-specific: marathon long runs may add tempo/marathon-pace finishes.',
      'Cap a single long run near ~30–35% of weekly volume.',
    ],
    prescription: {
      intensity: 'Predominantly Zone 2; optional MP segments late for marathon.',
      duration: 'Half: ~90–120 min; Marathon: progress toward ~28–32 km / up to ~2.5–3 h.',
      frequency: '1×/week.',
      progression: 'Lengthen gradually; insert a shorter "down" long run every 3–4 weeks.',
    },
    cautions: ['Jumping long-run distance too fast is a common injury cause.'],
    appliesTo: ['running','hybrid'],
    tags: ['long-run','endurance','marathon'],
    sources: ['Established science: marathon long-run progression literature; Daniels/Pfitzinger.'],
  },
  {
    id: 'running.recovery_run',
    domain: 'running', version: 1,
    title: 'Recovery / Easy Run',
    summary: 'Very easy running that promotes blood flow and consistency without adding meaningful fatigue.',
    principles: ['Slower than normal easy; purpose is recovery and frequency, not stimulus.', 'Optional — rest or cross-train are valid substitutes.'],
    prescription: { intensity: 'Zone 1 / very easy / fully conversational.', duration: '20–40 min.', frequency: 'As needed around hard days.', progression: 'n/a — keep easy.' },
    cautions: ['If it is not easy, it is not a recovery run.'],
    appliesTo: ['running','hybrid','hyrox'],
    tags: ['recovery','easy'],
    sources: ['Established science: recovery-run rationale; polarised-training easy-day principle.'],
  },
  {
    id: 'running.pacing_race_prep',
    domain: 'running', version: 1,
    title: 'Race Pacing & Specific Preparation',
    summary: 'As a race nears, training shifts toward goal-pace specificity and even/negative-split pacing discipline.',
    principles: [
      'Even or slightly negative splits beat positive splits at every distance.',
      'Final weeks rehearse goal pace and race-day fueling/logistics.',
      'Specificity rises as general volume tapers.',
    ],
    prescription: {
      intensity: 'Goal race pace; sharpen with race-pace segments.',
      duration: 'Race-pace volume scaled to distance (e.g. HM: 2–4×3–4 km @ HMP).',
      frequency: '1×/week race-specific session in the final block.',
      progression: 'Increase race-pace continuity, then taper volume ~1–2 weeks out.',
    },
    cautions: ['Do not introduce new intensities in the final 2 weeks.'],
    appliesTo: ['running','hybrid','hyrox'],
    tags: ['pacing','race-prep','specificity','taper'],
    sources: ['Established science: even-split pacing research; taper meta-analyses (Bosquet et al.).'],
  },
];
