// Knowledge domain: STRENGTH — force production, hypertrophy, concurrent training,
// movement quality, maintenance, fatigue. Established resistance-training science.

export const strength = [
  {
    id: 'strength.force_production',
    domain: 'strength', version: 1,
    title: 'Maximal Strength Development',
    summary: 'Maximal force is built with heavy loads, low-to-moderate reps, full recovery, and high movement quality.',
    principles: [
      'Heavy compound lifts drive neural and structural strength.',
      'Intensity (% 1RM) is the primary driver; keep reps in reserve to preserve quality.',
      'Long rests protect output and technique.',
    ],
    prescription: { intensity: '80–92% 1RM / RPE 7–9 (1–4 RIR).', duration: 'Mains 3–6 sets × 2–6 reps.', frequency: 'Each main pattern 1–3×/week.', rest: '2–5 min on mains.', progression: 'Add load when top set hits target reps at ≤ target RPE.' },
    cautions: ['Grinding to failure on heavy compounds spikes fatigue with little extra benefit.'],
    appliesTo: ['strength','hybrid','hyrox'],
    tags: ['strength','force','compound','1rm'],
    sources: ['Established science: ACSM resistance-training position stand; strength-intensity literature.'],
  },
  {
    id: 'strength.hypertrophy',
    domain: 'strength', version: 1,
    title: 'Hypertrophy & Volume Landmarks',
    summary: 'Muscle growth is driven primarily by weekly hard-set volume per muscle taken close to failure, within a recoverable range.',
    principles: [
      'Effective reps come from sets taken near failure (~0–4 RIR).',
      'Think in weekly sets per muscle group (volume landmarks), not per session.',
      'A wide rep range (≈5–30) grows muscle if effort is high.',
    ],
    prescription: { intensity: '60–80% 1RM / RPE 7–10 (0–3 RIR).', duration: '~10–20 hard sets/muscle/week (MEV→MAV).', frequency: 'Each muscle 2–3×/week.', progression: 'Add a set or small load weekly; back off near MRV.' },
    cautions: ['Junk volume past recoverable limits (MRV) reduces growth and adds fatigue.'],
    appliesTo: ['strength','hybrid'],
    tags: ['hypertrophy','volume','rir','landmarks'],
    sources: ['Established science: Schoenfeld volume meta-analyses; Israetel/RP volume landmarks (MEV/MAV/MRV).'],
  },
  {
    id: 'strength.concurrent_interference',
    domain: 'strength', version: 1,
    title: 'Concurrent Training & the Interference Effect',
    summary: 'Training strength and endurance together can blunt strength/power gains; the effect is manageable with smart sequencing.',
    principles: [
      'Interference rises with endurance frequency, duration and proximity to lifting.',
      'Separate high-intensity running and heavy lifting by ≥6–24h where possible.',
      'If same-day is unavoidable, prioritise the session that matters most for the goal first.',
      'Lower-body endurance interferes most with lower-body strength.',
    ],
    prescription: { frequency: 'Avoid hard run + heavy lower lift on the same/adjacent day in strength-priority phases.', progression: 'Bias volume toward the phase priority (strength vs endurance).' },
    cautions: ['Stacking VO2max work next to a heavy squat day is the classic hybrid mistake.'],
    appliesTo: ['hybrid','hyrox','strength'],
    tags: ['concurrent','interference','hybrid','sequencing'],
    sources: ['Established science: Hickson; concurrent-training meta-analyses (Wilson et al.).'],
  },
  {
    id: 'strength.muscular_endurance',
    domain: 'strength', version: 1,
    title: 'Muscular & Strength Endurance',
    summary: 'The ability to sustain force output under fatigue — central to HYROX/DEKA stations and compromised running.',
    principles: [
      'Higher reps, shorter rest, and circuit/EMOM formats build local endurance.',
      'Train the specific patterns under the specific fatigue of the event.',
    ],
    prescription: { intensity: '40–70% 1RM / RPE 7–9.', duration: '12–25+ reps, short rest, or time-based circuits.', frequency: '1–3×/week in a conditioning phase.', progression: 'Add reps/rounds or cut rest before adding load.' },
    cautions: ['Endless high-rep grinding erodes movement quality — keep technique standards.'],
    appliesTo: ['hyrox','deka','fitstop','hybrid'],
    tags: ['endurance','circuit','work-capacity'],
    sources: ['Established science: strength-endurance / local muscular endurance training literature.'],
  },
  {
    id: 'strength.movement_quality',
    domain: 'strength', version: 1,
    title: 'Movement Quality & Structural Balance',
    summary: 'Sound technique and balanced development across patterns underpin force, transfer and injury resistance.',
    principles: [
      'Cover the primary patterns: squat, hinge, push, pull, carry, lunge, brace.',
      'Balance pushing/pulling and knee/hip dominance to avoid asymmetry.',
      'Quality is a programmable standard, not an afterthought.',
    ],
    prescription: { progression: 'Earn load with positional quality; regress when form degrades.' },
    cautions: ['Loading dysfunction accelerates injury.'],
    appliesTo: ['strength','hybrid','hyrox','fitstop','deka'],
    tags: ['technique','balance','patterns'],
    sources: ['Established science: movement-pattern programming; structural-balance principles.'],
  },
  {
    id: 'strength.maintenance',
    domain: 'strength', version: 1,
    title: 'Strength Maintenance on Minimal Volume',
    summary: 'Strength is retained on far less volume than it took to build — useful in endurance-priority or time-poor phases.',
    principles: [
      'Maintaining intensity (heavy enough loads) preserves strength even as volume drops.',
      'As little as 1–2 quality sessions/week can hold strength for weeks.',
    ],
    prescription: { intensity: 'Keep loads high (≥80% 1RM on a few top sets).', duration: 'Minimal effective sets.', frequency: '1–2×/week.', progression: 'Hold, don\'t push, during the de-prioritised phase.' },
    cautions: ['Dropping intensity (not just volume) is what actually detrains strength.'],
    appliesTo: ['hybrid','hyrox','running'],
    tags: ['maintenance','minimal-dose','retention'],
    sources: ['Established science: detraining/maintenance literature (intensity preserves strength).'],
  },
];
